# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd72ade627954c9a183baf2c80d617b01327285f62b8e3e5d2091f7c4968d10afcd280cffb7252e8f8f2d33e07f74abc17c031297ab94ea882cf31d13d48d3c5

test:
  secret_key_base: 0fb98da5b23faac4ff9a623f76479b1362bb5d64d79412b7c548ebc80833a28d1666ebda9573cde63f18a1588df0a0eae218178110729837d3f7852adfcd53c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
